### ISSUE TITLE
multiplexing cell hashing minimum UMI

### ISSUE THREAD

**Issue by Jimmyyun** [Hoohm/CITE-seq-Count#118]
Hi, I hope you can help me with my trouble.

How much do you expect to have a minimum UMI count per cell to separate multiplexing (let's say two samples) based on CITE-seq-count? 
In my case, I was getting around 70~90 mean UMI count per cell in HTO library. The cutoff was used as about 40 UMI count. 
Do you think it's simply due to a lack of sequencing depth? Could you share your experience?

Thanks so much!
Jimmy

**Comment by Hoohm** [comment]
Hello @Jimmyyun 

I don't have much experience with cell hashing myself sadly.
Do you have difficulty separating your samples?

**Comment by Jimmyyun** [comment]
Hi @Hoohm 
It's more like too much negative versus singlet and doublet. I figure it could be a lot because of experimental issue but I was wondering whether analysis might affect the result as well.

**Comment by Hoohm** [comment]
Just to be sure, are you using a 10x v3 kit or is it home made?

**Comment by Jimmyyun** [comment]
I've used both v3 and v3.1.

**Comment by Hoohm** [comment]
It's a computational issue probably then.
Please refer to this: https://hoohm.github.io/CITE-seq-Count/Guidelines/#10xv3

Here is a bit of code to help out: https://gist.github.com/Hoohm/edf05b544105cd3f396d6e8c5dd66b22

**Comment by Jimmyyun** [comment]
why do you think it could be a computational issue? I thought it could be simply due to experimental issue that antibody barcodes couldn't amplify enough? I do see lots of similar UMIs such as 35, 40 between two multplexed samples. Then, it considers them as "negative".

**Comment by Hoohm** [comment]
If it's what I think it is, it's a "translation" issue.
10xv3 holds two different cell barcodes in each cell. One for the RNA and one for the antibody tag.

This means that if you use the mRNA cell barcodes to filter out CSC output, you probably won't find the cells you are looking for.

**Comment by Jimmyyun** [comment]
We did combine between mRNA cell barcodes and HTO cell barcodes. I thought that's what you want to look at eventually. Ideally, don't you want to find specific cells you can get matching information between RNA and HTO cell barcodes?

**Comment by Hoohm** [comment]
Maybe I'm not explaining it in the right way.

Did you use a whitelist to run CSC on your data?

**Comment by Jimmyyun** [comment]
yup we used a whitelist to run CSC

**Comment by Hoohm** [comment]
And this whitelist came from the filtered RNA data?

**Comment by Jimmyyun** [comment]
No, it didn't. But we used 3M whitelist. We are testing two things now: the one with filtered RNA data cell barcode; the other with CSC expected cell without 10xv3 whitelist.

**Comment by Hoohm** [comment]
Ok, I can tell you that the one with the filtered barcodes will probably not make sense.

I would use the top cells instead of the whitelist.

Once you have done this, if you could send me the barcodes.tsv file, I'll help you out.

**Comment by Hoohm** [comment]
Hello @Jimmyyun 
has this been resolved?

**Comment by Jimmyyun** [comment]
Hi @Hoohm 
Sorry about the delay. We still think it is due to experiment issue. We used the top cells instead of the whitelist, but the result was similar as previous one. We were still getting lots of negative. Around 65% negative, 32% singlet, 3% doublet. We will run another experiment with different setup and see how it looks.

**Comment by Hoohm** [comment]
Did you try the conversion of the barcodes with the code I sent out?

**Comment by Jimmyyun** [comment]
yes I did.

**Comment by LorenzoTomassoni** [comment]
Hi @Hoohm,

I am experiencing the same problem described above. I run CITE-Seq-count in order to generate an HTO UMI matrix from the R1 and R2 fastq files that contain only the sequences of the hashing antibodies (10x - cell ranger). I have created a .csv file with the TAGs and the code worked reasonably well (about 95% of mapped reads). But my problem is the follwing:

1) when I run CITE-Seq-count without whiteList, the top 3000 barcodes  in the HTO matrix do not match at all the barcodes that I have in the gene-expression single-cell matrix.

2) when I run CITE-Seq-count providing as whiteList the barcodes that I have in the single-cell gene-expression matrix the resulting HTO matrix returned by cite-Seq-count contains almost all zeros. 

So, in case 1) I am not able to demultiplex the cells because the barcodes are different from the ones returned by cellRanger
In case 2) I am not able to divide the cells as well according to the different conditions because the HTO matrix is too sparse and any further down stream analysis would be meaningless.

Can you please help me? Or do you have any suggestions?

Thanks

**Comment by Hoohm** [comment]
Hello @LorenzoTomassoni 

You should use [this code](https://gist.github.com/Hoohm/edf05b544105cd3f396d6e8c5dd66b22) to "translate" the whitelist you got.

I'm working on having a fix in CSC but it's not going to be available very soon.

**Comment by LorenzoTomassoni** [comment]
Hello @Hoohm,

thanks for your answer. I'll try that and I'll let you know

**Comment by LorenzoTomassoni** [comment]
Hi @Hoohm,

I have used the code you provided me to "translate" the barcodes and it actually worked. The results I got in the downstream analysis are significantly improved. 

I have another question in order to be sure that I am correctly applying CITE-Seq to my data. 
The fastq files that I have (R1 and R2 from 10x cell ranger) contain sequences that are 101 bp long and they have the following structure:
R2: contains the antibody tag (16bp starting at a fix position after the first 10bp in all the sequences)
R1: contains cell barcodes starting at the beginning of the sequence. 
That's why I am running CITE-Seq with the following input parameters:
-cbf 1 -cbl 16 -umif 17 -umil 26 --start-trim 10.
But I got the following Warning: Read1 length is 101bp but you are using 26bp for cell and UMI barcodes combined. This might lead to wrong cell attribution and skewed umi counts.

Do you have any suggestions for that? The point is that I don't know why my R1-fastq file is 101bp even if the barcode and UMI should be 16bp and 10bp respectively for 10x.

Thanks

**Comment by Hoohm** [comment]
@LorenzoTomassoni don't worry about the warning. It's there mostly to check that people don't get the positions wrong.

CSC will just discard the bases that are not useful.
If you can sequence less, 26bp is what you need. The rest is wasted money.

**Comment by LorenzoTomassoni** [comment]
Hi @Hoohm. Thanks for your answer, and that is exactly what I understood going through the code of CSC (the warning should not affect the results).
