### ISSUE TITLE
Bug in multiple file preprocessing:

### ISSUE THREAD

**Issue by DSJM** [Hoohm/CITE-seq-Count#122]
def get_read_paths(read1_path, read2_path):
    """
    Splits up 2 comma-separated strings of input files into list of files
    to process. Ensures both lists are equal in length.
    Args:
        read1_path (string): Comma-separated paths to read1.fq
        read2_path (string): Comma-separated paths to read2.fq
    Returns:
        _read1_path (list(string)): list of paths to read1.fq
        _read2_path (list(string)): list of paths to read2.fq
    """
    _read1_path = read1_path.split(',')
    _read2_path = read2_path.split(',')
    **if len(read1_path) != len(read2_path):**
        sys.exit('Unequal number of read1 ({}) and read2({}) files provided'
                 '\n Exiting'.format(len(read1_path),len(read2_path)))
    return(_read1_path, _read2_path)

This line must be if len(_read1_path) != len(_read2_path), as the program should check that we have an equal amount of files and not characters in the path. 

Sorry for not making a pull request and solving it myself, but I am pretty new to programming :)

**Comment by Hoohm** [comment]
Thanks for the catch @DSJM 
If you want, I can wait and let you learn with this small fix on how to contribute to projects on github.

Here are the steps you would need to take.

1. fork the repo. This is because you can't modify code on repos you are not a owner of.
2. git clone your repo on your computer.
3. make the change.
4. `git add` the processing.py file. You can check the path with `git status`.
5. `git commit -m 'fixed bug #122'`
6. `git push`. This will push your commit to your master branch
7. Come here again and make a pull request from your master to my master.

I'll merge it when it's here :)

**Comment by akingu** [comment]
Hi @Hoohm and @DSJM ,

I'm trying to process multiple files (hashed sample run over two 10X GEMs and 2 sequencing lanes). I'm new to github and am not a programmer. Thank-you for putting this package together @Hoohm and for spotting the bug@DSJM!-are you going to fork the repo and make a pull request? Sorry, I don't know what the etiquette here is and don't want to pressure anyone or add to anyone's workload but would love this bug fixed :)

**Comment by cpflueger2016** [comment]
Hey @akingu, it's probably easiest for you to merge the fastq files per read (e.g. read1) from the different lanes into one file. For example, you could use a command like this one:

`cat seqXYZ_S1_L001_R1_001.fastq.gz seqXYZ_S1_L002_R1_001.fastq.gz > seqXYZ_merged_R1.fastq.gz`

Same thing for read2 of course. That should help you in the interim. Good luck!

**Comment by Hoohm** [comment]
The bug is fixed in the next release but in the meantime, having the names of the files match in terms of number of characters also fixes it.

**Comment by akingu** [comment]
@cpflueger2016 @Hoohm -awesome. Thanks!

**Comment by Hoohm** [comment]
This is now fixed in 1.4.4
