### ISSUE TITLE
'RuntimeError: dictionary keys changed during iteration' when correcting UMIs

### ISSUE THREAD

**Issue by lxhuang7** [Hoohm/CITE-seq-Count#125]
Hi @Hoohm, 

In [#110](https://github.com/Hoohm/CITE-seq-Count/issues/110) you mentioned a fixed bug in v1.4.3. However, I still got the error message using v1.4.3 for demultiplexing HTOs. I would appreciate if you could provide some guidance on solving this problem. Thanks!

Lei

$ CITE-seq-Count --version
CITE-seq-Count v1.4.3

$ CITE-seq-Count -R1 $fq1 \
        -R2 $fq2 \
        -t $TAGLIST \
        -cbf 1 \
        -cbl 16 \
        -umif 17 \
        -umil 26 \
        -cells 10000 \
        -n 20000 \
        -o $OUTDIR/results \
        --debug

'Mapping done for process 100188. Processed 20,000 reads
Mapping done
Correcting cell barcodes
Looking for a whitelist
Collapsing cell barcodes
Correcting umis
Traceback (most recent call last):
  File "/gpfs/data/bioinformatics/software/miniconda3/envs/citeseq/bin/CITE-seq-Count", line 8, in <module>
    sys.exit(main())
  File "/gpfs/data/bioinformatics/software/miniconda3/envs/citeseq/lib/python3.8/site-packages/cite_seq_count/__main__.py", line 435, in main
    ) = processing.correct_umis(
  File "/gpfs/data/bioinformatics/software/miniconda3/envs/citeseq/lib/python3.8/site-packages/cite_seq_count/processing.py", line 229, in correct_umis
    for TAG in final_results[cell_barcode]:
RuntimeError: dictionary keys changed during iteration'

**Comment by robinfchan** [comment]
Related to a bug fix in Python >3.8:

https://community.atlassian.com/t5/Jira-Core-questions/RuntimeError-dictionary-keys-changed-during-iteration-when/qaq-p/1245641

Trying to modify the dictionary which iterating thru it will throw this error if running CITE-seq-Count with python 3.8. Make sense since modifying the iterator within the loop isn't great haha.

Going to try to re-run while forcing Python 3.7 for a temp fix. This probably will be irrelevant in the next release of CSC since umi correction is going paralell, so not gonna bother trying to fix the function myself.

**Comment by robinfchan** [comment]
@lxhuang7 

Yup, can confirm that UMI correction works fine now running it with Python 3.7.7.

**Comment by Hoohm** [comment]
Ok I get it now.
I do change the dict by updating the counts for a specific barcode.
This doesn't change the order/flow of the iteration but replaces a value. I guess python 3.8 is more strict about this.
I'll be sure to fix it in the parallel implementation.

Thanks for this :)

**Comment by lxhuang7** [comment]
@robinfchan, it works under python 3.7. Thank you!

**Comment by tdanhorn** [comment]
This has not been fixed so far, and it makes it impossible to use a Python version >3.7.  For anyone interested, there is a trivial fix:

```
--- lib/python3.9/site-packages/cite_seq_count/processing.py.orig       2019-10-05 09:12:45.000000000 -0600
+++ lib/python3.9/site-packages/cite_seq_count/processing.py    2020-12-01 19:22:55.519271533 -0700
@@ -226,7 +226,7 @@
     corrected_umis = 0
     aberrant_umi_count_cells = set()
     for cell_barcode in top_cells:
-        for TAG in final_results[cell_barcode]:
+        for TAG in list(final_results[cell_barcode]):
             n_umis = len(final_results[cell_barcode][TAG])
             if n_umis > 1 and n_umis <= max_umis:
                 umi_clusters = network.UMIClusterer()
```
(If I understand this correctly, it iterates over a copy of the keys of the dictionary, so it does not care that the underlying dictionary gets modified.)  I don't know enough about the underlying mechanisms of Python to judge whether it is good idea to do this or if it just masks dirty code, but it will run (tested with Python 3.9.0) and you can trivially modify your installation until an official fix is released.

**Comment by Hoohm** [comment]
It definitely helps but the main problem is that it creates a copy of all the barcodes which can be heavy depending on how deep it was sequenced.

I'm struggling to keep up with new releases because of a lot of other projects in parallel.

Thanks for the quick fix though, I'm sure some people might want ot use it :)

**Comment by tdanhorn** [comment]
Actually, the copy is just for the tags of a single cell (barcode), if I am reading this right, so it should not be so bad in terms of space (time may still be affected, as it would happen for all cells, but then this is Python, not C).
But I took a harder look at the code and found that in the line following the `pop(TAG)`, the new result gets assigned to the very same key (`TAG`), so the pop seems entirely unnecessary, as the new result will just overwrite the old one.  So a much cleaner fix is simply to get rid of the call to `pop()`:
```
--- lib/python3.8/site-packages/cite_seq_count/processing.py.orig       2019-10-05 09:12:45.000000000 -0600
+++ lib/python3.8/site-packages/cite_seq_count/processing.py    2020-12-05 15:23:48.872615838 -0700
@@ -233,7 +233,7 @@
                 UMIclusters = umi_clusters(
                     final_results[cell_barcode][TAG],
                     collapsing_threshold)
-                (new_res, temp_corrected_umis) = update_umi_counts(UMIclusters, final_results[cell_barcode].pop(TAG))
+                (new_res, temp_corrected_umis) = update_umi_counts(UMIclusters, final_results[cell_barcode][TAG])
                 final_results[cell_barcode][TAG] = new_res
                 corrected_umis += temp_corrected_umis
             elif n_umis > max_umis:
```
To confirm that it works, I ran a real-world sample with >63M reads and the UMI matrices are identical to the one with the `list()` fix (except for the order of the columns, which is random).  The new fix is 7.4% faster than the old one in run (and CPU) time (can't compare to the original because that crashes with Python >3.7, but eliminating a function call should increase efficiency, if anything).
Depending on your planned release schedule it could make sense to have an intermediate bug fix release if you agree with this fix.

**Comment by Hoohm** [comment]
Turns out the pop was the culprit.
I've done a minimal test to see if indeed it fixed it and it does. It also seems to not reloop over the new entries as it did before, explaining the faster runtime :)

Sorry for taking so long for such a minimal issue. I was hoping to release all of this way faster and didn't want to mess around merge conflicts.

There it is, 1.4.4, please let me know if it fixed it for you.

**Comment by tdanhorn** [comment]
Works as expected, thank you!
