### ISSUE TITLE
Cell BC filtering despite --bc_collapsing_dist 0

### ISSUE THREAD

**Issue by codymowery** [Hoohm/CITE-seq-Count#130]
Hi Patrick,

Like everyone else here, I first want to say thanks for making (and maintaining!) such a great resource. Excellent work.

I am just starting to use the package after having written some custom scripts (without any collapsing or error correction) for tag mapping, but first wanted to compare mapping and assignment. It looks like read and UMI counts are 100% the same, but I am seeing some barcodes that are recovered by my code but aren't in the CITE-seq-Count outputs. Admittedly, these barcodes are a small fraction of the total cells and they have long homopolymer sequences (i.e. AAAAAAAACAAAAACC, TTTTTGGTGGTAATAG, etc...).

That being said, I couldn't see anything in the package documentation about cell barcode filtering independent of the `--bc_collapsing_dist` argument. Can you provide some info about the filtering criteria you apply when calling cell barcodes? My full command is below for reference.

Thanks!

`CITE-seq-Count -R1 S14_L004_R1_001.fastq.gz -R2 S14_L004_R2_001.fastq.gz -t ../bcs.csv -trim 26 -cbf 1 -cbl 16 -umif 17 -umil 26 -cells 3000 --bc_collapsing_dist 0 --umi_collapsing_dist 0 --no_umi_correction --max-error 0 --dense`

**Comment by Hoohm** [comment]
Hello @codymowery 
Happy to hear you like the tool!

The only filtering is the number of cells you are asking or the whitelist you would provide.

In your case, `--cells 3000`, means that you will only get the top 3000 most present barcodes, hence missing the low ones you might get if you don't filter at all.

I've tried not to mess with the data too much so there is no other filter (except the barcode you might lose because of correction)

I hope this helps :)
