### ISSUE TITLE
memory / cpu requirements

### ISSUE THREAD

**Issue by kzalocusky** [Hoohm/CITE-seq-Count#18]
Greetings,

I've been attempting to run the CITE-seq-Count script on our server. My job keeps getting killed, I presume because it has outgrown my estimated memory/CPU requirements. Can you provide a rule of thumb about how many cores / how much memory I should request? I have a 10x run with a whitelist of about 16,000 sample barcodes.

Thanks,
Kelly

**Comment by santiagorevale** [comment]
Hi Kelly,

The program keeps in memory the following:
- tags/ABs list (small file)
- whitelist of cell barcodes (small file)
- the sequence string of each Read1 and Read2 (this is big)
e.g.
Read1: length 26 bp; count 1,000,000
Read2: length 98 bp; count 1,000,000
Kept in memory (26+98) * 1,000,000 = 124,000,000 bytes = 124 Mb per million pair of reads

Of course this is a rough estimate, because data structures also occupy space, but on the other hand, exact duplicate reads are removed.

Regarding CPU requirements, it's not multi-threaded, so only one core is being used.

I hope you find this information useful.

Cheers,
Santiago

**Comment by Hoohm** [comment]
Hello @kzalocusky 
I'm testing a mutli processing implementation which will reduce the amount of memory required to run the program. This version doesn't load all the reads in memory but processes them on the fly with a generator.
I've tested it on a 12 million read dataset with 8 tags and it used around 1.2 GB of ram.

Number of threads is also going to be an option. The workload is split by the number of threads available.

You can test it out on [this branch](https://github.com/Hoohm/CITE-seq-Count/tree/feature/multi_processing)

**Comment by Hoohm** [comment]
This should be better with the latest version.
Feel free to reopen it if necessary.
