### ISSUE TITLE
Extracted ADT cell Barcodes do not match those found in the STAMPS

### ISSUE THREAD

**Issue by JulianSpagnuolo** [Hoohm/CITE-seq-Count#20]
After extracting the top 3000 ADT counts, I was surprised that only about half of these barcodes was present in the cell barcode read counts file output from the dropseq-tools pipeline.

Is this due to the barcode synthesis correction step in the dropseq pipeline?

Do you have plans to integrate this script with that pipeline in order to take advantage of their barcode error detection/correction? It should not be too much of an issue since the pipeline extracts the cell and UMI barcodes from read 1 and adds them to the XC and XM tags, respectively, of the resulting BAM/SAM file.

**Comment by Hoohm** [comment]
Hello @JulianSpagnuolo 
I missed your issue sorry for the late response.
You will almost always see a discrepancy between rna and tag data for droplet based protocols. This is because the lowest RNA content cells that might not be selected in the end will still be valid from a tag perspective.

As an example, High mitochondrial/dying cells will come up with tags but won't be kept for RNA because of the low amount RNA.

There is not cell barcode correction in CITE-seq-Count, so you definitely lose a few reads. But the sensitivity of CITE-seq is so high that I would not worry about this.

You can "adjust" this by using a whitelist of cell barcodes. Either take the top cells in RNA and use those for the tags or the other way around. You could also be very broad and take the union of top cells from each.

There is definitely an incentive to integrate both data in dropSeqPipe. It will be done in the future, but there is no fixed plan as for a specific release date yet.

**Comment by JulianSpagnuolo** [comment]
Thanks @Hoohm , thanks for the feedback, I have found that it is better to use cell barcodes that have high antibody counts to find the "good" cell barcodes in the transcriptome data (because of the high sensitivity of the method).
As for the barcode correction - I have already gone ahead and written my own Rcpp solution (currently available on my git: julianspagnuolo/adtseq) that is compatible with the dropseq-tools pipeline written by @jamesnemesh 
I also modified the antibody barcode detection to take into account the phred quality of the base call since I was concerned about mismatches at low quality base-calls (not always a problem but I had a bad sequencing library to get data from).
