### ISSUE TITLE
Memory, missing barcodes, and R2 trimming

### ISSUE THREAD

**Issue by chris-mcginnis-ucsf** [Hoohm/CITE-seq-Count#24]
Hello!

First off, thanks so much for providing this tool for the single-cell community. I've been using cite-seq count regularly over the last few months and I've found one potential bug and have a couple of features that I'm hoping you could implement.

1. Bug: Occasionally when I use CSCount to align barcode reads to a 96-index reference using the following example script:

python /bin/CITE-seq-Count \
    -R1 /alpha/cmcginnis/NUC_BAR/NUC_BAR_S10_L001_R1_001.fastq.gz \
    -R2 /alpha/cmcginnis/NUC_BAR/NUC_BAR_S10_L001_R2_001.fastq.gz \
    -t /alpha/cmcginnis/CSCount/LMOlist.csv \
    -cbf 1 -cbl 16 -umif 17 -umil 26 -tr "[ATCG]{8}[A]{6,}" -hd 1 \
    -wl /alpha/cmcginnis/NUC_L1_WL.txt \
    -o CSCount_NUC_wWL_111518.tsv

I receive an output where not all 96 barcodes are present (e.g., For the instance posted above, only 23/96 barcodes were present in the final csv). It's worth noting that this usually happens when I'm processing experiments in which I do not utilize all 96 barcodes -- for 96-plex experiments, I normally get 96 barcodes back -- and the barcodes I expect to be present never drop out. I figured that there may be a barcode QC step that removes barcodes with sufficiently few aligned reads, but when I look at my final count matrix, there are plenty of barcodes with exactly 0 UMIs. 

2. Suggested Features: When I try to use CSCount on fairly large barcode FASTQs, I have to be very careful in terms of memory usage. I'm wondering if you could incorporate multi-thread processing into CSCount or, alternatively, load only enough of R2 to enable alignment (e.g., 18 bases instead of all 96). I believe either of these solutions would speed up CSCount tremendously and/or allow multiple instances to be run on a single core.

**Comment by Hoohm** [comment]
Hello @chris-mcginnis-ucsf and sorry for the late response, this issue has slipped through :(

On the plus side, the [multi_processing](https://github.com/Hoohm/CITE-seq-Count/tree/feature/multi_processing) branch is actually implementing the parallelization you asked for. The memory amount has also been drastically decreased and using a whitelist speeds up the processing because I don't deal with the reads that are not in the whitelist.

Using a whitelist for cell barcodes now also adds the missing ones, even if nothing matched to them. This was implemented a few versions ago. Which version are you using?

**Comment by Hoohm** [comment]
This has been fixed in the latest version.
Feel free to reopen it if necessary.
