### ISSUE TITLE
UMI number over 20k

### ISSUE THREAD

**Issue by Kailewang** [Hoohm/CITE-seq-Count#50]
Hi, thanks for developing this tools. I have some cell-hashing data, and the umi number of some of the cells are over 20,000. After running this, I got an uncorrected_cells folder in which contains cells with ultra-high UMI count. However, when I merge this file with results in umi_count folder, and check the UMI count distribution, I found there is a big gap between this two data set (umi_count: 1,000-13,802, uncorrected: 20,001-46,428), looks there is no any middle value between 13,802-20,001, this is very weird, and looks not right. And I also test other dataset, they all have this problem. Not sure what's happened...

**Comment by Hoohm** [comment]
Hello @Kailewang 
the uncorrected data has no umi correction happening. This means that all cell-TAG combination under 20'000 are actually corrected. So I'm not surprised that you see a gap between the uncorrected and the corrected.
Have you looked at the read counts instead? You should not see a gap there because you count all the reads and there is no influence from UMI correction.

**Comment by Kailewang** [comment]
Thanks for the quick reply, but why don't correct the UMI with high density? Sometimes they are very useful too.

**Comment by Hoohm** [comment]
This is a performance issue right now. A lot of users reported CITE-seq-Count running for days and being stuck at UMI correction. I'm working on a long term fix but in the meantime, this is the workaround that I'm using.

Normally those super high UMI-TAG are linked to aggregated cells which you normally don't keep. How many uncorrected cells do you actually get in the end?

**Comment by Kailewang** [comment]
Thanks, got it! Most of my samples only around 10, but 1 sample I got over hundreds. I have one more question, if we correct the UMIs from scRNA-seq data, that is make sense, because you can based on the R2 sequence, if R2 is same, cell barcode is same, 1-2 base UMI difference has great chance that come from sequencing error since the diversity of R2. But for hashing barcodes, usually, R2 is hashing barcode, and most of them should be identical in one cell, how you correct them? For me, 1-2 base UMI difference may also have great chance to be real, not the sequencing error.

**Comment by Hoohm** [comment]
I'm not sure I understand what you mean by 

> For me, 1-2 base UMI difference may also have great chance to be real, not the sequencing error.

Are you saying your different hashing barcodes are similar to each other? This would be a design flaw as you should be able to differentiate hashing barcodes properly.

If you're asking how the hashing barcodes are counted, CITE-seq-Count will map the reads onto your hashing barcodes. You can specify how many mismatches you want with the option `--max-errors X`. There is check in place which will compare your hashing barcodes to each other and test if the max errors you provided is too much and would make a distinction impossible.

**Comment by Kailewang** [comment]
Sorry for this confusion, I mean --umi_collapsing_dist parameter.

**Comment by Hoohm** [comment]
Ok I understand your question. You're saying that cell hashing having the same hash but with different umis could be fused where they should not be.

I don't think this is a problem. UMI length is usually 10bp, meaning 4^10=1'048'576

Since we work in the range of tens of thousands, the chance we merge two actual real UMIs is still very low. I would not worry about this atm, it might be different in the future if we keep increasing the number of different UMIs that are collected.

**Comment by Hoohm** [comment]
@Kailewang I think this question has been answered. If you need more info please reopen the issue.
