### ISSUE TITLE
CITE-seq-Count with v3 vs v2 chemistry

### ISSUE THREAD

**Issue by lshepard2154** [Hoohm/CITE-seq-Count#55]
Hello Christoph,

This is a general question/thread regarding the differences in the need to use CITE-seq-Count across different 10X chemistries. I am part of a group which will soon start CITE-seq with both 10X chemistries, and would like feedback about some aspects of the analysis:

1) Since the release of TotalSeq B which is compatible with Feature Barcoding and v3 chemistry, it seems to me that `cellranger count` will provide all outputs needed to run the analysis in Seurat. Thus, am I correct in the understanding that users will no longer need to run `CITE-seq-count`?

2) If using V2 chemistry from 10X, my understanding is that `cellranger` will not be able to analyze the antibody reads. In this case, is the following correct? RNA reads can be aligned with `cellranger count` (version 2 or 3), but CITE-seq (antibody reads), can only be analyzed with `CITE-seq-count`? And then the outputs of the above can be added to Seurat 3.

3) On the same note as above, I am a bit confused why the original [CITE-seq paper](https://www.nature.com/articles/nmeth.4380) utilized the Drop-seq pipeline to analyze 10X v2 chemistry? Why not cellranger, such as what was[ done in this preprint, which you are an author (I am assuming v2 chemistry was used here, although it is not mentioned)?](https://www.biorxiv.org/content/10.1101/460147v1) Also the original CITE-seq paper doesn't mention the use of CITE-seq-Count, but I am assuming that it was actually utilized in the analysis but not yet released to the public at the time correct?

One last naive question, but for the sake of being clear (I do not have CITE-seq data yet so I wanted to ensure my interpretation of your documentation is correct). You mention that we need a `tags.csv` file for CITE-seq-Count. I am assuming that these barcodes and the names of the tags/antibodies are provided by the company (e.g.: [BioLogend, such as the one shown here for TotalSeq A](https://www.biolegend.com/totalseq)) or the sequencing core correct? Just wanted to double-check!

__Thanks a lot for all the clarification__. This information seems to be a bit sparse currently online, so it is a bit difficult to link it all together when we consider multiple versions of CITE-seq/10X chemistries.

**Comment by Hoohm** [comment]
Hello @lshepard2154 

I think you have mistaken me with Christoph from the Satija lab. Although the first prototype was drafted by Christoph, he did not work on CITE-seq-Count after that.

1. Cellranger provides antibody counting for V3. CITE-seq-Count is only needed if you are using cell hashing on top of it which cellranger does not provide support.
2. You are correct. Antibodies were introduced with the V3 chemistry so for v2 you need to manually add them during your experiment and then run CITE-seq-Count on it.
3. I could not tell you why this was done using drop-seq tools instead of cellranger, you should ask Christoph directly.
4. Yes, the link you provide shows the tags that are required by the software.


I'm currently testing CITE-seq-Count on the V3 chemistry comparing the results. While doing this, I found out that V3 is using an odd cell barcoding strategy and will report this in the documentation. I might expand a bit on older chemistries there as well, maybe this would help regroup some of the relevant information for CITE-seq-Count usage.

I hope this helps, let me know if you have other questions.

Best wishes

Patrick Roelli

**Comment by lshepard2154** [comment]
Hello @Hoohm!

Yes, I am sorry for the confusion about the names, but my questions were intended to you as the primary author of CITE-seq-Count! :) (the cite-seq.com website lists you and Christoph as the developers for this, so I assumed he was checking this repository too. But like you said, his involvement was initially, and this is under your account. Apologies again!).

* One clarification for you answer ( number 2): as a whole it does seem that using cellranger on RNA reads (v2 or v3) + CITE-seq-Count on antibody reads would then be the correct strategy to analyze the data correct? I will ask Christoph about his reasoning behind using the Dropseq pipeline, but wanted to make sure that the cellranger + CITE-seq-Count pipeline also works first.

I am very much looking forward to your updated documentation with your current test. It would be very interesting to know more about the V3 strategy. And if you update the docs with the older chemistries, I do believe that this will benefit the community!

Thank you very much for the additional clarification.

**Comment by joonlee3** [comment]
10X v3 chemistry include more cell barcodes in their whitelist (3M. For v2, 700K). It seems to significantly increase the data processing time.

When I have fastq files from multiple lanes, I think there are two ways to process ADT/HTO data.

1. Run CITE-seq-count with each pair of fastq files and combine the ADT/HTO count matrices
2. Combine fastq files and run CITE-seq-count with the combined fastq files

Which one do you recommend? Do you expect any differences between two final outputs?

Best,
Joon

**Comment by Hoohm** [comment]
There is a catch with the new V3 chemistry. 10x decided to create a [mapping](https://github.com/10XGenomics/cellranger/tree/master/lib/python/cellranger/barcodes/translation) between cell barcodes from RNA and cell barcodes from ADT. Meaning you have to use the mapping to match the output of the ADT if you do it with CITE-seq-Cout instead of cellranger.

Right now I'm trying to allow CITE-seq-Count to run on the V3 whitelist without it being too long but I am not successful for now. I don't have much free time to work on it right now.

As for your question, combinning the files is the probably the best way to do it. I would imagine a difference between the two. Since we are collapsing UMIs from the same data but on different lanes, I expect you will overestimate the counts if you run CITE-seq-Count on each lane separately because you are not totally collapsing the UMIs.

**Comment by Hoohm** [comment]
Hello @lshepard2154,

Going to close this and add some information about this problem in the documentation.

**Comment by kaizen89** [comment]
Hi @Hoohm, I have a pair of fastq files which contain both RNA and ADT. I am not sure if I have to run cellranger on this to get the output of ADT? Is it normal to specify the same fastq file for cellranger in the library.csv file with both Gene Expression and Antibody Capture?
