### ISSUE TITLE
CITE-seq-Count requires -cells/--expected_cells when whitelist is provided

### ISSUE THREAD

**Issue by MaxKman** [Hoohm/CITE-seq-Count#56]
Hi,

thanks for developing CITE-seq-count. I switched to the newest version yesterday. I noticed that it failed to run when provided with a whitelist of barcodes with the error message:

> CITE-seq-Count: error: the following arguments are required: -cells/--expected_cells

The complete command I run goes like this:
`CITE-seq-Count -R1 fastq/ADT_R1.fastq.gz -R2 fastq/ADT_R2.fastq.gz -t barcodes_ADT.csv -u results_ADT/unmapped.csv -cbf 1 -cbl 16 -umif 17 -umil 26 -wl barcode_whitelist/barcode_whitelist.txt -o results_ADT/`

Did the syntax change or is -wl just ignored?

I could get it to run by providing -cells as
`cell_num=$(wc -l < barcode_whitelist/barcode_whitelist.txt)`

but I am not sure if the whitelist is then used when processing the reads.

Best Max

**Comment by Hoohm** [comment]
Hello @MaxKman,

As of today, if you provide the whitelist, the --cells argument is not necessary. It's actually not used. The main idea was that if people used a a small whitelist from the RNA data, it would be easier to get the exact corresponding TAG data.

I'm thinking of changing this in the future because I'd like to be able to use raw whitelists instead of trimmed ones.

For now, I'd advise you to use --cells 0 as input.

**Comment by MaxKman** [comment]
Using a  small whitelist generated from the RNA data is exactly what I am doing. Are you saying I can now leave out the --cells argument or shall I set it to 0?

**Comment by Hoohm** [comment]
You can set it to 0

**Comment by Hoohm** [comment]
Closing this as the question has been answered
