### ISSUE TITLE
Adjustments for sequencing

### ISSUE THREAD

**Issue by danmoore1987** [Hoohm/CITE-seq-Count#71]
Hi Patrick, thank you for the great tool!

We have some questions on the old CITE-seq-Count that had "Bad Antibody structure" output vs the current one, and how to adjust for our current sequencing platform.

We now sequence TotalSeqA libraries on their own now using a Next-seq kit. Because the Next-seq handles low complexity libraries poorly. After the 15bp barcode(+B) gets sequenced we now get either PolyA or G. The G is outputed if it repeated encounters the same nucletoide across all transcripts (which is A) in consecutive cycles. In other words does the current CITE-seq counter assume 15bp-B-GGG as an error so throws it out? If doesn't throw it out, great. If it throws it out, how would you adjust the parameters to permit counting them in using your package? We use totalseqA + v3 kit.

Kind regards,
Moore

**Comment by Hoohm** [comment]
Hello @danmoore1987 

The new versions don't check for the bad structure anymore. This was a legacy constraint when the technology was still young. The base "B" is not checked anymore. It's just the 15bp mapping or not and it doesn't care about the GGG or AAA after the 15th base.

bad_struct is replaced by unmapped and incloses any read which doesn't map or has too many errors.

I suggest you run the new version on the old dataset and compare it with the new to see how different it is.

One thing you will see is that the number of UMI will decrease since now we do umi and barcode correction.

Let me know how it compares.

**Comment by danmoore1987** [comment]
Hi @Hoohm,

Thank you for the prompt reply! Will test out.

**Comment by Hoohm** [comment]
Hello @danmoore1987,
any news regarding this issue?

**Comment by Hoohm** [comment]
Closing this for now, feel free to reopen.
