### ISSUE TITLE
Need support for multiple input reads

### ISSUE THREAD

**Issue by arkal** [Hoohm/CITE-seq-Count#77]
Sequencing a single cell library across multiple lanes is common practice and cite-seq-count should be able to handle that and not expect the user to merge them downstream. 

FYI: I've locally cloned and written code to do this but can't push a PR without collaboration privileges.

**Comment by Hoohm** [comment]
Hello @arkal 

You are right, this should be easier. I'm finishing my PhD and the main focus not being on CITE-seq-Count I tend to focus on issues that are "more problematic" and urgent rather than quality of life.
That being said, I really appreciate you offering your contribution or any other help.

Here is the easiest way to make a PR:

1. Fork the repo first
2. Clone your repo locally
3. make your changes
4. commit and push your changes to the forked repo.

Once this is done you can make a PR request.

I'll try to make the review process as fast as possible.

Let me know if you need more help to do it, I'll gladly assist you.

**Comment by arkal** [comment]
Haha i know that feeling. I can do this and make the PR

**Comment by Hoohm** [comment]
Hello @arkal 
I'm wrapping things up for the new release. It's merged in the develop branch.
It's working for me. Can you test it out as well?

**Comment by Hoohm** [comment]
I wanted to let you know that I messed up the PR request workflow.
Still haven't figured out how to do it properly to credit you directly on the platform.
You are cited in the changelog though. Is that ok with you?

**Comment by arkal** [comment]
It's not ideal but it's ok if it's too hard to fix it!

**Comment by Hoohm** [comment]
The new release is out and it has integrated your changes!

Thanks a lot and sorry for the bad PR workflow.
