### ISSUE TITLE
memory handling on large datasets 

### ISSUE THREAD

**Issue by bridenrd** [Hoohm/CITE-seq-Count#86]
Hi, I have some data from a Nextseq run, about 370M reads.

My VM is 16 cores, 128GB of RAM, but during the Mapping process the software quickly consumed all of the available memory and crashed.   See the attached chart, the memory consumption seems to grow exponentially.

![memory](https://user-images.githubusercontent.com/1762747/66234267-1d2ba200-e6a2-11e9-914a-60679a2a30d3.png)

I'm interested to hear any suggestions on how to get this data analyzed.   Any idea how to determine how much RAM is required?   Or is there a way to get it done within the limits of this machine.    Can the software even support this?      

Thanks!!

**Comment by Hoohm** [comment]
Hello @bridenrd,
large dataset are a challenge for CITE-seq-Count because the dict is completely stored in memory.
One solution that I have started to look at is to use a reddis implementation and store is on the drive instead. This might take a while to implement because I don't have much time to work on CITE-seq-Count these days.

I'm going to add a section on the README looking for someone who would know how to implement a reddis version and hope I find someone to help out to get it faster.

For now sadly, I don't have a good solution for this issue.

I've heard good things about [BUStools](https://github.com/BUStools/bustools) and it should handle big datasets pretty well and in a timely manner.

I hope this helps.

**Comment by Hoohm** [comment]
Forgot to mention, using less cores will also use less memory since each dict is duplicated for each core. Maybe you can find a sweetspot that will run slower but will deal with the memory issue.

**Comment by bridenrd** [comment]
Thanks for the quick feedback Patrick.   I tried fewer cores but it didn't complete.   The dict object just doesn't scale well, looks like some people go with SQLlite.  I hadn't heard of redis, but will check it out.  Also looking into Kallisto/Bustools.    Best regards  --rob
