### ISSUE TITLE
How to combine multiple donor tag libraries?

### ISSUE THREAD

**Issue by molybdenumt** [Hoohm/CITE-seq-Count#87]
What is the best way to combine multiple donor samples of 10x? 
I have 4 hashtag libraries and 4 mRNA libraries. Normally for 10x samples without hashtags , I would use cellranger agg to combine the mRNA libraries. But I don't know what to do with the hashtag libraries?

I've been using Seurat to analyze my data. Should I use that to combine the samples? Do I need to use the Findintegrationanchors and Integratedata functions in Seurat? I don't know if these functions are comparable to cellranger agg.

**Comment by Hoohm** [comment]
Hello @molybdenumt 
just to be sure, when you say 4 hashtag libraries, it's the same cells and hashtags, right?
In other words, one experiment but 4 lanes?

**Comment by molybdenumt** [comment]
Kind of. I have 1 experiment with 2 donors. 2 hashtag libraries and 2 mRNA libraries each donor. Sorry I know it's a bit complicated. Each hashtag library uses the same oligo sequence but for different conditions. 
For example: 
Donor 1 : hashtag library A and hashtag library B , mRNA lib A and mRNA lib  B
hashtag library A (2 conditions): media, rna
hashtag library B (2 conditions): rnase, dna

Donor 2:  hashtag library C and hashtag library D , mRNA lib C and mRNA lib D
hashtag library C (2 conditions): media, rna
hashtag library D (2 conditions): rnase, dna

I hope that makes more sense.

**Comment by Hoohm** [comment]
So hashtags are fine since you have one per donor/condition.
The other important thing is to have a list of cell barcodes that are not overlapping.
If I understood you correctly, this should be fine for you.
In the end you have mixed all 4 libraries together for one run on the chromium.

You can use the new feature of giving multiple lanes as input instead of concatenating everything in one file.

In Seurat there is a function called HTODemux that should get you what you need.

**Comment by molybdenumt** [comment]
I have always done aggregation using cellranger agg. Are you saying I should just stick with seurat and not use cellranger agg at all?

**Comment by molybdenumt** [comment]
It’s okay. I figured it out. I use the merge function for the different samples. Then normalize them. Thank you.

**Comment by Hoohm** [comment]
Ok, can I close this then?

**Comment by molybdenumt** [comment]
Yes
