### ISSUE TITLE
Questions about data/matrix structure and expected cell counts

### ISSUE THREAD

**Issue by cpcook1** [Hoohm/CITE-seq-Count#89]
Hi I am relatively new to scRNA-seq analysis and had some questions about some data that we were processing. We are using Chromium 10x v3.

1) We processed some ADT data with CITEseq-Count where we have 25 antibodies and about 6000 expected cells. For the CITEseq-Count input of this run we set expected cells = 0; and used a whitelist from 10x that had 737,280 cell barcodes. We ran this and the resultant matrix we got was, not surprisingly 25 x 737,280. I removed all columns from the matrix with 0's and this truncated it down to 418,045 columns. This is far more columns than we have cells. What exactly is the data that is mapping here I cant understand? How can there be more columns than cells? The matrix was too big to process in seurat to analyze the data and we look for other solutions. I have pasted the output of this run below if you are interested. Sorry the formatting did not transfer over.

**Date: 2019-09-17
Running time: 13.0 hours, 15.0 minutes, 32.69 seconds
CITE-seq-Count Version: 1.4.2
Reads processed: 48330610
Percentage mapped: 97
Percentage unmapped: 3
Uncorrected cells: 0
Correction:
Cell barcodes collapsing threshold: 1
Cell barcodes corrected: 128766
UMI collapsing threshold: 2
UMIs corrected: 7935276
Run parameters:
Read1_filename: /home/R1_001.fastq.gz
Read2_filename: /home/R2_001.fastq.gz
Cell barcode:
 First position: 1
 Last position: 16
UMI barcode:
 First position: 17
 Last position: 26
Expected cells: 0
Tags max errors: 2
Start trim: 0**

2) So we then discarded the whitelist, and set the expected number of cells to 6000. This returned a matrix 25 x 6000, with, from what we can tell clean looking data we could analyze in seurat. But now I am worried that since this matrix is filled, if CITE-seq Counts is not analyzing or picking up some reads had we set the cell number larger? Obviously we don't have exactly 6000 cells. How would we know exactly how many cells we had, and why does the program not spit out the actual number of cells (greater or lower) than what is inputted? I have pasted the output to this run below:

**Date: 2019-10-08
Running time: 1.0 hour, 30.0 minutes, 51.65 seconds
CITE-seq-Count Version: 1.4.2
Reads processed: 48330610
Percentage mapped: 97
Percentage unmapped: 3
Uncorrected cells: 0
Correction:
Cell barcodes collapsing threshold: 1
Cell barcodes corrected: 138808
UMI collapsing threshold: 2
UMIs corrected: 7949601
Run parameters:
Read1_filename: /home/R1_001.fastq.gz
Read2_filename: /home/R2_001.fastq.gz
Cell barcode:
 First position: 1
 Last position: 16
UMI barcode:
 First position: 17
 Last position: 26
Expected cells: 6000
Tags max errors: 2
Start trim: 0**

3) For both the first run, and this second run, whether I load in the matrices from umi_count, or from read_count, the matrices are the same. The read_count data should be larger no? I guess I don't understand fully the difference between umi_count and read_count

4) I don't understand what it means by Cell barcodes corrected. Could you perhaps explain or point me to some sources where I can learn more about this correction and what is happening with the reads and the data?

Thanks so much if you take to the time to answer my questions I am really appreciative

-Chris

**Comment by Hoohm** [comment]
Hello @cpcook1 
Welcome to the single-cell world! I'll try to help you out :)

1. You are using 10x V3 but you got a 700k cell whitelist. I'm afraid there is a discrepancy here. 10x V3 has 3.6M whitelist (which is not public for now) and a ~7.2M whitelist that is available on their github.
I highly recommend not using the 7.2M list but the output of the filtered RNA cells from cell ranger instead. If you're using your own antibody TAGS and not the 10xV3 ones, you're good to go with this info.

2. I suggest you take more cells than expected so that you are certain you find the ones you actually have. You can also use the filtered out cells from cellranger as an input in CITE-seq-Count.

3. That is strange. Normally umi counts should be lower than read counts. Is it a 100% similar matrix? Could you make a plot comparing the sum of each cell for UMI and read counts?

4. Sequencing errors are common and since sometimes a cell barcode might have a mistake. This means that you lose a read if the barcode is not a 100% match. That's why we do cell barcode correction. Similarly, we do UMI correction to collapse UMIs with errors.

Hope this helps, let me know if something is unclear.

**Comment by cpcook1** [comment]
Thanks so much this was really helpful. I'm going to run rerun CITEseq Count with maybe 20,000 cells and see what happens. We don't have a cellranger output for this data set (yet) so I cant take the output from there at this time.

About the Umi and Read, thanks this was a bonehead error. The dimensions of the matrix were the same, the counts were very different.

**Comment by cpcook1** [comment]
Interesting thank you so much for your response. We will end up using the ADT data only in some cases. In this case, I'm guessing it would be best to filter out the low-end UMI garbage? Perhaps for this we could make a histogram with UMI counts on the x axis and frequency on the y axis and kill the bottom x%, or maybe anything thats 2 SD's away from the mean?

The last question I have is from here:

> If you don't intend to use cells that only have protein counts in your analysis, I'd recommend to use the 5200 cells from cellranger as a whitelist.

Does cellranger output an actual barcode list for each cell it finds, and that can be used as input into CITEseqCount or did you mean just set the expected cells to 5200. If the former, where is this information in the cellranger output?

Thank you again I really appreciate the help

**Comment by happar73** [comment]
With regard to the first point, it seems it would be better to filter out with the read counts rather than the UMI counts right. If you did filter out from the read_counts matrix how could one easily transfer the set of filtered cells to the umi_count matrix?

**Comment by cpcook1** [comment]
With regard to the first point, it seems it would be better to filter out with the read counts rather than the UMI counts right. If you did filter out from the read_counts matrix how could one easily transfer the set of filtered cells to the umi_count matrix?

**Comment by Hoohm** [comment]
If you want the cells that have only TAGS even though they don't have transcripts, then use the `--cells` argument, I would suggest a bit more than expected to be sure you get all the cells. (ie 6000)

Cellranger provides a filtered out transcript umi cout matrix. You can use the cell names from this matrix as a whitelist.

In regards to your second comment, I'm not sure what you mean by filtering out by the read counts rather than the umi counts. The only difference between both matrices is the range of the counts. The dimensions are the same.

**Comment by cpcook1** [comment]
Thanks so much I have been working on these things the past week and everything makes more sense now. Thanks again!

**Comment by Hoohm** [comment]
Happy to help!
I'll close this now. Feel free to reopen if needed.
