### ISSUE TITLE
problem with --bc_collapsing_dist 0 in 1.4.3

### ISSUE THREAD

**Issue by ChristophH** [Hoohm/CITE-seq-Count#92]
The specific output I see is
```
Mapping done for process 42487. Processed 1,000,000 reads
Mapping done
Correcting cell barcodes
Looking for a whitelist
Collapsing cell barcodes
Traceback (most recent call last):
  File "/usr/local/bin/CITE-seq-Count", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/cite_seq_count/__main__.py", line 394, in main
    ab_map=ordered_tags_map)
  File "/usr/local/lib/python3.7/site-packages/cite_seq_count/processing.py", line 336, in correct_cells
    ab_map=ab_map)
  File "/usr/local/lib/python3.7/site-packages/cite_seq_count/processing.py", line 284, in collapse_cells
    for real_barcode in true_to_false:
TypeError: 'NoneType' object is not iterable
```
If I change `--bc_collapsing_dist` to `1` there are no problems. 

If this is not a general problem, I'll try to make a minimal reproducible example.

**Comment by Hoohm** [comment]
Hello @ChristophH 
I see what the problem is. I'm working on a small update that should come out soon, it will be added in there.Thanks for the catch!

**Comment by Hoohm** [comment]
CSC is now skipping this step if it's 0.
It's on the develop branch. I'm gonna release the new version as soon as some people have tested their issues.

**Comment by codymowery** [comment]
Hi @Hoohm,

I am still running into the same problem above, even after installing the develop version via code below.. Any tips? Thanks!
`git clone https://github.com/Hoohm/CITE-seq-Count.git
cd CITE-seq-Count
git checkout develop
python3.6 setup.py develop`

**Comment by Erinke89** [comment]
Dear @Hoohm,
Has your updated code been included in version 1.4.4? I upgraded CSC but I still get exactly the same error as pasted above when running with --bc_collapsing_dist at 0 (and not at 1).
Thank you

**Comment by Erinke89** [comment]
Dear @Hoohm,
Could I please ask for your help, because I'm stuck. Can you tell me which part of the code should be adjusted to fix this error? I managed to install the develop branch and indeed I no longer get this error, but now I get a different problem. The names from the tag list csv file are no longer imported into the output, only the tag barcodes... 
I'm not sure if I should be using the develop branch at all to get reliable results. Maybe I can adjust only that part of the code that fixes the above error.

Many thanks in advance!
Erinke

**Comment by Hoohm** [comment]
Very strange,

the latest iteration should be on the branch feature/barcode_translation.

But I think the problem comes from the fact that you use the gene column=1
option when reading the data.

I've change this a bit and now the default is column 2, as a normal mRNA
MTX from 10x would be produced.

Can you double check that the features.csv file only has one column?

**Comment by Erinke89** [comment]
Sorry I edited my comment when I found out indeed there were 2 columns in features.csv file before I noticed your reply.

Thank you for making the branch for me! I will use that one then!
